# Generated by Django 3.1.2 on 2021-01-14 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Долгота')),
                ('altitude', models.IntegerField(verbose_name='Высота')),
                ('total', models.IntegerField(verbose_name='Глобальная интенсивность')),
                ('Bx', models.IntegerField(verbose_name='Bx')),
                ('By', models.IntegerField(verbose_name='By')),
                ('Bz', models.IntegerField(verbose_name='Bz')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('race', models.CharField(max_length=10, verbose_name='Рейс')),
                ('takeoff', models.CharField(max_length=50, verbose_name='Взлет')),
                ('landing', models.CharField(max_length=50, verbose_name='Посадка')),
            ],
        ),
        migrations.DeleteModel(
            name='AirPlane',
        ),
        migrations.AddField(
            model_name='dataflight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.route'),
        ),
    ]
