# Generated by Django 3.1.2 on 2021-01-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210114_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflight',
            name='dirction',
            field=models.IntegerField(default=0, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='dataflight',
            name='time',
            field=models.CharField(default='', max_length=50, verbose_name='Время'),
        ),
    ]
